window.AMA_PLAYERS = [
  {
    "name": "방소윤",
    "generation": "47기",
    "position": "윈터 of 공간 에스파",
    "number": "#10",
    "age": "2005년생",
    "hometown": "전라남도 장흥",
    "instagram": "itsme_soyun",
    "department": "공간정보공학과",
    "studentId": "24학번",
    "mbti": "INFJ",
    "favoriteTeam": "아마축구부⚽️",
    "favoritePlay": "그냥 잘하기",
    "hobby": "새벽산책하기",
    "favoritesong": "빅뱅 - Blue",
    "drinkingCapacity": "소주 3잔반ㅎㅎ",
    "drinkingHabit": "집가기",
    "strength": "귀여움ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ",
    "weakness": "생각이 너무 많음",
    "favoriteFood": "마라탕",
    "idealType": "다정하면서 남자다운 사람, 육군, 운전병, 축구 잘하는 사람",
    "motto": "모든 일의 시작은 나를 믿는 것으로부터",
    "tmi": "아축과 미팅 2번 해봤습니다!ㅋㅋㅋ",
    "image": "image2/IMG_1475.jpg",
    "group": "YB",
    "rolemodel": "고대영 선배님ㅎㅎ"
  },
  {
    "name": "정주영",
    "generation": "41기",
    "position": "아축 아빠?로서 이성적? 판단?을 담당한다고 함?",
    "number": "#12(인데 지훈에게 뺏김)",
    "age": "2000년생",
    "hometown": "부산광역시",
    "department": "도시공학과",
    "studentId": "19학번",
    "graduationYear": "2026년",
    "favoriteTeam": "FC서울, 리버풀FC",
    "favoritePlay": "사이드에서 속도붙여서 오버래핑하는 클래식한 풀백스타일을 좋아하지만 언더래핑도 시도중",
    "hobby": "축구 직관가기",
    "favoriteFood": "파스타(거의 이탈리아계 한국인 수준, 집에서 바질도 키움)",
    "motto": "소선대악 대선비정",
    "bestMoment": " ",
    "messageToJuniors": " ",
    "image": "image2/정주영.jpg",
    "group": "OB",
  },
  {
    "name": "박대원",
    "generation": "45기",
    "position": "ST",
    "number": "#9",
    "age": "2003년생",
    "hometown": "서울특별시",
    "instagram": "iam_dae1",
    "department": "건축공학과",
    "studentId": "23학번",
    "mbti": "ISFJ",
    "favoriteTeam": "맨체스터 시티, 아마축구부",
    "favoritePlay": "침투파",
    "hobby": "인생에 대한 고찰",
    "favoritesong": "빅나티 - 뻔한 발라드",
    "drinkingCapacity": "1병/h",
    "drinkingHabit": "?",
    "strength": "배려, 존중, 이해, 따뜻함",
    "weakness": "부끄러움이 많음",
    "favoriteFood": "옥수역 김밥친구들",
    "idealType": "예쁘고 착하고 말 잘 통하는 사람",
    "motto": "준비된 자만이 기회를 잡는다",
    "tmi": "나무위키에 있음 [박대원(2003)]",
    "image": "image2/박대원.jpg",
    "group": "YB",
    "rolemodel": "이순신"
  },
  {
    "name": "이유찬",
    "generation": "44기",
    "position": "MF",
    "number": "#43",
    "age": "2002년생",
    "hometown": "강원도 화천",
    "instagram": "ychn.2",
    "department": "수학과",
    "studentId": "22학번",
    "mbti": "INTJ",
    "favoriteTeam": "FC 바르셀로나",
    "favoritePlay": "패스 or 드리블로 압박빠져나오기, 1대1 돌파",
    "hobby": "읽기",
    "favoritesong": "이문세 - 기억이란 사랑보다",
    "drinkingCapacity": "반병",
    "drinkingHabit": "집에 가기",
    "strength": "오래 참는다",
    "weakness": "진지함",
    "favoriteFood": "양고기",
    "idealType": "아직 잘 모르겠네요",
    "motto": "안해서 후회하기보다는 차라리 하고서 후회하기",
    "tmi": "매번 지하철을 탈 때마다 어르신들이 항상 한번정도 길을 여쭤보신다",
    "image": "image2/logo.png",
    "group": "YB",
    "rolemodel": "윈스턴 처칠"
  },
  {
    "name": "양채원",
    "generation": "47기",
    "position": "골을 넣으면 환호하는 포지션입니다",
    "number": "",
    "age": "2006년생",
    "hometown": "전라남도 여수",
    "instagram": "chaaee.e",
    "department": "영어영문학과",
    "studentId": "25학번",
    "mbti": "INTP",
    "favoriteTeam": "아마축구부🧎‍♂️",
    "favoritePlay": "저는 압도적인 축구실력으로 혼자서 모든걸 해내는 솔로 플레이를 주로 하고 있습니다",
    "hobby": "",
    "favoritesong": "",
    "drinkingCapacity": "한병",
    "drinkingHabit": "솔직해짐",
    "strength": "착함",
    "weakness": "설거지하는 속도가 느림",
    "favoriteFood": "샤브샤브",
    "idealType": "잘 웃는 사람",
    "motto": "착하게 살자",
    "tmi": "고등학생 때 꼬리벼 부상으로 방석을 가지고 다녔는데 치질이라고 소문나서 억울했어요",
    "image": "image2/logo.png",
    "group": "YB",
    "rolemodel": ""
  },
  {
    "name": "전유나",
    "generation": "47기",
    "position": "8번 공격수 원해요",
    "number": "",
    "age": "2006년생",
    "hometown": "전라남도 목포",
    "instagram": "jyn8_xx",
    "department": "영어영문학과",
    "studentId": "25학번",
    "mbti": "ESFP",
    "favoriteTeam": "아마축구부, 친오빠팀",
    "favoritePlay": "만들어가다가 돌파~~!~!!",
    "hobby": "",
    "favoritesong": "",
    "drinkingCapacity": "한병...?",
    "drinkingHabit": "잠",
    "strength": "밝음",
    "weakness": "걱정많음",
    "favoriteFood": "고기 밥 디저트",
    "idealType": "잘해주고 운동 잘하는 사람, 나 웃게해주는 사람!",
    "motto": "행복하고 건강하게 살자",
    "tmi": "키 162인 줄 알았는데 최근 164.7로 업데이트됨",
    "image": "image2/logo.png",
    "group": "YB",
    "rolemodel": ""
  },
  {
    "name": "김영준",
    "generation": "45기",
    "position": "RB",
    "number": "#17",
    "age": "2003년생",
    "hometown": "서울특별시",
    "instagram": "kdosa_wns",
    "department": "국사학과",
    "studentId": "23학번",
    "mbti": "ISTP",
    "favoriteTeam": "토트넘, FC서울",
    "favoritePlay": "상대 기어다닐 때까지 돌리다가 골 넣는 척 골대 앞에서 또 돌리다가 그러다가 슛하는 척 다시 주고 골",
    "hobby": "해외축구 분석",
    "favoritesong": "식케이 - LOV3",
    "drinkingCapacity": "1잔",
    "drinkingHabit": "축구 이야기 무한대 on",
    "strength": "끈기, 성실함",
    "weakness": "주장이 매우 강함",
    "favoriteFood": "골목순대국(사을 도봉구 도봉로133길 41) 여기 아니면 순대국 안 먹습니다",
    "idealType": "성실하고 현명한 사람이면서 에쁜 사람",
    "motto": "나를 죽이지 못하는 고통은 날 더 강하게 만든다",
    "tmi": "윤여준 27년 10월 전역 수고해라 ㅋㅋ",
    "image": "image2/logo.png",
    "group": "YB",
    "rolemodel": "박지성"
  },
  {
    "name": "장주혁",
    "generation": "47기",
    "position": "RW",
    "number": "#51",
    "age": "2003년생",
    "hometown": "경기도 용인",
    "instagram": "vvngur_3",
    "department": "신소재공학과",
    "studentId": "22학번",
    "mbti": "ISFP",
    "favoriteTeam": "FC 바르셀로나",
    "favoritePlay": "사이드에서 일대일하기, 냅다 뛰기",
    "hobby": "롤",
    "favoritesong": "한로로 - 입춘",
    "drinkingCapacity": "반병",
    "drinkingHabit": "벽에 기대기, 엎드려 자기",
    "strength": "착함, 감정기복이 별로 없음",
    "weakness": "낯을 많이 가림",
    "favoriteFood": "버거킹 통새우와퍼",
    "idealType": "털털하고 예쁜 사람",
    "motto": "어떻게든 되겠지",
    "tmi": "밥먹는 속도가 느려서 친구들하고 먹으면 욕 많이 먹음",
    "image": "image2/장주혁.jpg",
    "group": "YB",
    "rolemodel": "손지한"
  },
  {
    "name": "김빈",
    "generation": "46기",
    "position": "술자리 참여 포지션임다 ^^",
    "number": " ",
    "age": "2002년생",
    "hometown": "광주광역시",
    "department": "조경학과",
    "studentId": "21학번",
    "graduationYear": " ",
    "favoriteTeam": "전북현대, 레알 마드리드",
    "favoritePlay": "야무진 빌드업 후 골 넣기(무조건 넣어야지 도파민 터져함)",
    "hobby": "",
    "favoriteFood": "한식이면 무조건!!!",
    "motto": "그래도 해야지 어떡해",
    "bestMoment": " ",
    "messageToJuniors": " ",
    "image": "image2/김빈.jpg",
    "group": "OB",
  },
  {
    "name": "김경아",
    "generation": "45기",
    "position": "매니저 및 회식 참여(였으나 바빠서 임시휴업)",
    "number": " ",
    "age": "2000년생",
    "hometown": "경기도 안양",
    "department": "조각학과(G)",
    "studentId": "26학번 새내기 ^^",
    "graduationYear": "",
    "favoriteTeam": "FC안양, 레알 마드리드",
    "favoritePlay": "역전승이 짜릿하지",
    "hobby": " ",
    "favoriteFood": "한식 알라뷰",
    "motto": "낭만을 즐기며 행복하게 긍정적이게~",
    "bestMoment": " ",
    "messageToJuniors": " ",
    "image": "image2/김경아.jpg",
    "group": "OB",
  },
  {
    "name": "요셉",
    "generation": "47기",
    "position": "WF, ST",
    "number": "#82",
    "age": "2005년생",
    "hometown": "이라크+인천",
    "instagram": "a_yu_sf",
    "department": "도시공학과",
    "studentId": "25학번",
    "mbti": "INTP",
    "favoriteTeam": "레알 마드리드",
    "favoritePlay": "내 골 위한 플레이",
    "hobby": "드라마, 영화 시청",
    "favoritesong": "Rothy - 잠이 오지 않는 밤에",
    "drinkingCapacity": "반병",
    "drinkingHabit": "착해짐(평소에도 착함.)",
    "strength": "스피드, 논스톱 슛, 터치",
    "weakness": "체력, 나태함",
    "favoriteFood": "쭈꾸미 볶음밥, 오징어 덮밥",
    "idealType": "아일릿 민주, 수지",
    "motto": "인생은 혼자다",
    "tmi": "인생 반을 한국에서 살아서 반한국인임",
    "image": "image2/요셉.jpg",
    "group": "YB",
    "rolemodel": "호날두"
  },
  {
    "name": "강현진",
    "generation": "45기",
    "position": "CB",
    "number": "#5",
    "age": "2002년생",
    "hometown": "경기도 안양",
    "instagram": "k_hyunjin121",
    "department": "신소재공학과",
    "studentId": "23학번",
    "mbti": "ISFJ",
    "favoriteTeam": "레알 마드리드",
    "favoritePlay": "롱킥을 통한 역습, 뒷공간 부수기, 시원한 중거리",
    "hobby": "요리, 여행",
    "favoritesong": "coldplay - everglow",
    "drinkingCapacity": "2병",
    "drinkingHabit": "멀쩡한 척 하기",
    "strength": "끈기, 성실, 잘먹음",
    "weakness": "생각이 많음, 허리디스크",
    "favoriteFood": "돼지갈비, 양고기",
    "idealType": "털털하고 밝은 사람",
    "motto": "지나고 보면 별거 없다",
    "tmi": "비빔면 4개로 배 안 참",
    "image": "image2/강현진.jpg",
    "group": "YB",
    "rolemodel": "39기 김동완"
  },
  {
    "name": "이석희",
    "generation": "47기",
    "position": "MF",
    "number": "#72",
    "age": "2004년생",
    "hometown": "충청남도 천안",
    "instagram": "tjrgml2",
    "department": "생명과학과",
    "studentId": "25학번",
    "mbti": "ISFJ",
    "favoriteTeam": "수원삼성 블루윙즈",
    "favoritePlay": "패스, 탈압박",
    "hobby": "축구 하기, 축구 보기",
    "favoritesong": "창모 - hotel room",
    "drinkingCapacity": "소주 세 잔",
    "drinkingHabit": "잠",
    "strength": "친해지면 재밌다",
    "weakness": "친해지기 어렵다",
    "favoriteFood": "면",
    "idealType": "눈이 예쁜 사람",
    "motto": "남에게 피해주지말자",
    "tmi": "이정효 감독님 사랑합니다💙🤍❤️",
    "image": "image2/이석희.jpg",
    "group": "YB",
    "rolemodel": "이정효 감독"
  },
  {
    "name": "김진유",
    "generation": "46기",
    "position": "LB",
    "number": "#19",
    "age": "2005년생",
    "hometown": "세종특별자치시",
    "instagram": "jinyu_0809",
    "department": "국제관계학과(행정학과 복수전공)",
    "studentId": "24학번",
    "mbti": "ESTJ",
    "favoriteTeam": "대전하나시티즌, 토트넘 홋스퍼, 아마축구부, 인테르(시립대)",
    "favoritePlay": "상대 윙의 1대1 돌파를 막거나 뒷공간 역습을 커버하는 수비",
    "hobby": "야구, 축구 보기, 헬스, 사이클링, 낚시, 뉴스 시청, 음주",
    "favoritesong": "The Weeknd - Less Than Zero",
    "drinkingCapacity": "2.5병",
    "drinkingHabit": "동어반복",
    "strength": "노빠꾸, 악바리, 츤데레, 빠름, 왼발잡이",
    "weakness": "노빠꾸, 술고래, 화가 많음, 발밑, 핸들과 브레이크가 고장난 8톤 트럭",
    "favoriteFood": "삼겹살",
    "idealType": "고양이상, 운동 좋아하는 여자",
    "motto": "No Pain, No Gain",
    "tmi": "전공 수업시간에 아마축구부 골키퍼 유니폼 입고 발표하다가 교수님이랑 30분동안 말싸움하고 축구하러간다고 수업 나간 적 있음(ㄱㅁㅈ 교수님 죄송합니다...)",
    "image": "image2/김진유.jpg",
    "group": "YB",
    "rolemodel": "44기 이재훈(축구만)"
  },
  {
    "name": "장민준",
    "generation": "47기",
    "position": "GK",
    "number": "#84",
    "age": "2006년생",
    "hometown": "서울특별시 중랑구",
    "instagram": "m7nzun",
    "department": "국제관계학과",
    "studentId": "25학번",
    "mbti": "INFP",
    "favoriteTeam": "리버풀",
    "favoritePlay": "골만 안 먹히면 됩니다",
    "hobby": "",
    "favoritesong": "",
    "drinkingCapacity": "",
    "drinkingHabit": "자기",
    "strength": "친해지면 활발해지기",
    "weakness": "낯가리기",
    "favoriteFood": "치킨",
    "idealType": "예쁜 사람",
    "motto": "실수해도 정신차리자",
    "tmi": "",
    "image": "image2/장민준.jpg",
    "group": "YB",
    "rolemodel": ""
  },
  {
    "name": "김상윤",
    "generation": "44기",
    "position": "MF",
    "number": "#6",
    "age": "2002년생",
    "hometown": "서울특별시",
    "instagram": "yxxn_sang0_0",
    "department": "환경공학부",
    "studentId": "22학번",
    "mbti": "ESTP ENTP 왔다갔다함",
    "favoriteTeam": "없는데, 그나마 뮌헨?",
    "favoritePlay": "티키타카, 수적 우위를 통한 이득 창출 플레이",
    "hobby": "동생들 괴롭히기",
    "favoritesong": "엘가 - 사랑의인사",
    "drinkingCapacity": "2병",
    "drinkingHabit": "취침",
    "strength": "너무 잘생겼다, 리더쉽을 갖췄다, 열정이 있다",
    "weakness": "잘생겼다, 치명적이다, 건강이 안좋다.",
    "favoriteFood": "햄버거, 피자",
    "idealType": "적당히 마르고, 피부 하얗고, 웃는게 예쁜 사람",
    "motto": "1초의 시간도 돈으로 주고 살 수 없다",
    "tmi": "요즘 얼굴 폼 좋음",
    "image": "image2/김상윤.jpg",
    "group": "YB",
    "rolemodel": "39기 용교수님, 심선생님"
  },
  {
    "name": "김영우",
    "generation": "47기",
    "position": "RB, RW",
    "number": "#3",
    "age": "2000년생",
    "hometown": "경기도 안산",
    "instagram": "young_woo12",
    "department": "도시공학과",
    "studentId": "23학번",
    "mbti": "ISTP",
    "favoriteTeam": "바르셀로나",
    "favoritePlay": "거친 플레이",
    "hobby": "야구",
    "favoritesong": "권진아 - 운이 좋았지",
    "drinkingCapacity": "2병",
    "drinkingHabit": "집가기",
    "strength": "포기를 안한다",
    "weakness": "게으름",
    "favoriteFood": "삼겹살",
    "idealType": "귀여운 사람",
    "motto": "흘러가는대로 살자",
    "tmi": "X",
    "image": "image2/김영우.jpg",
    "group": "YB",
    "rolemodel": "부모님"
  },
  {
    "name": "최재혁",
    "generation": "47기",
    "position": "벤치포함운동장모든곳",
    "number": "#33",
    "age": "2005년생",
    "hometown": "최재혁그는누구인가롯데자이안쓰의연고지인부산광역시출생이자수인분당선망포역이생기기도전에신영통을개척한YMCA아기스포츠단과경희대학교국제캠퍼스에서불과3분거리인영일초등학교펜실베니아주립대학교의위성도시스테이트칼리지시의RadioParkElementarySchool그리고영일초등학교옆에있는영일중학교그리고또머나먼워싱턴주킹카운티벨뷰시의TyeeMiddleSchool그리고또또의대호소인들의국룰루트인상산고등학교를졸업한글로컬보이머드블러드그자체로본가질문을받으면곤란해하곤한다",
    "instagram": "jaelayki",
    "department": "생명과학과",
    "studentId": "25학번",
    "mbti": "ENFJ",
    "favoriteTeam": "아스날",
    "favoritePlay": "크로스 원터치 마무리",
    "hobby": "해외축구 전술 분석",
    "favoritesong": "기리보이 - 사랑할 수 없는 이유",
    "drinkingCapacity": "한병",
    "drinkingHabit": "좋아하는 형아들에게 앵기기",
    "strength": "조버의 총애를 받는 롱스로인",
    "weakness": "외데고르 뺨치는 약발",
    "favoriteFood": "지코바숯불양념치킨반마리+현미밥",
    "idealType": "귀여운 눈나",
    "motto": "이 사랑에 후회란 없어",
    "tmi": "축구로 우울할 필요 없어. 인생이 더 중요",
    "image": "image2/최재혁.jpg",
    "group": "YB",
    "rolemodel": "데클란 라이스"
  },
  {
    "name": "이재훈",
    "generation": "44기",
    "position": "CB, LW",
    "number": "#98(곧 변경 예정)",
    "age": "26세(만으로..)",
    "hometown": "세종씨리",
    "instagram": "do_after_mcnal",
    "department": "탑 시크릿입니다..",
    "studentId": "",
    "mbti": "ESFP",
    "favoriteTeam": "전북현대",
    "favoritePlay": "스피드로 상대를 압도하는 플레이",
    "hobby": "축구, 영화 가끔, 코노 달리기, 산책 등등등",
    "favoritesong": "이보람 - 처음 그 자리에, 버나드 박 - 솔직히 말해서, 히게단 - Pretender",
    "drinkingCapacity": "한..2병?",
    "drinkingHabit": "만취하면 깨물어요.",
    "strength": "pk 잘 막음(나름 키퍼출신임), 그래도 속도에선 아축 내에서 1등을 자신함(빈센트 제외), 작은 육각형 전 포지션 가능..",
    "weakness": "pk 못참(진짜임), 리프팅 5개 이상 못함(진짜임)",
    "favoriteFood": "맥도날드",
    "idealType": "웃는게 이쁜 사람, 눈빛 하나로 빠져들게 만드는 사람. 행동의 진심을 알아봐주는 사람, 내 개그(?)에 웃어주는 사람.",
    "motto": "간절하게 절실하게 더 높이 더 멀리",
    "tmi": "첫인상이 빡세보여도, 깐깐하고 어려워보여도 친해지면 이만큼 단순한 사람이 없으니.. 많이 다가와주세요 친구들.. 잘 부탁해요~",
    "image": "image2/이재훈.jpg",
    "group": "YB",
    "rolemodel": "이재훈 빠덜 이재훈 마덜"
  },
  {
    "name": "고경표",
    "generation": "44기",
    "position": "MF",
    "number": "#54",
    "age": "2003년생",
    "hometown": "전라남도 목포",
    "instagram": "gogogogo_rae",
    "department": "국사학과",
    "studentId": "22학번",
    "mbti": "INFJ",
    "favoriteTeam": "에버튼",
    "favoritePlay": "쉽게쉽게 내주기",
    "hobby": "아축 활약상 시청",
    "favoritesong": "파테코 - 널 떠올리는 중이야",
    "drinkingCapacity": "1병",
    "drinkingHabit": "더 마시다가 자기",
    "strength": "뻔뻔한 연상미",
    "weakness": "신장",
    "favoriteFood": "제육, 국밥, 고기",
    "idealType": "귀여운 사람",
    "motto": "피해끼치지 말자",
    "tmi": "배고프면 예민해짐",
    "image": "image2/고경표.jpg",
    "group": "YB",
    "rolemodel": "김상윤"
  },
  {
    "name": "박준호",
    "generation": "47기",
    "position": "FW",
    "number": "#79",
    "age": "2003년생",
    "hometown": "경기도 성남시",
    "instagram": "bag_juno343",
    "department": "통계학과",
    "studentId": "23학번",
    "mbti": "ISFJ",
    "favoriteTeam": "토트넘 홋스퍼, 성남FC",
    "favoritePlay": "뒷공간 침투. 간결한 전개",
    "hobby": "FC온라인",
    "favoritesong": "한로로 - 시간을 달리네",
    "drinkingCapacity": "1병",
    "drinkingHabit": "잠이 쏟아짐",
    "strength": "근면 성실",
    "weakness": "유머 부족",
    "favoriteFood": "면 요리",
    "idealType": "취향 비슷하고 말 잘 통하는 고양이상",
    "motto": "안 되면 될 때까지",
    "tmi": "한 명 차이로 22학번이 되지 못했다는...",
    "image": "image2/박준호.jpg",
    "group": "YB",
    "rolemodel": "기안84"
  },
  {
    "name": "이태훈",
    "generation": "47기",
    "position": "RB",
    "number": "#31",
    "age": "2006년생",
    "hometown": "경상남도 김해",
    "instagram": "taeguri0611",
    "department": "행정학과",
    "studentId": "25학번",
    "mbti": "ISTJ",
    "favoriteTeam": "토트넘, 바르셀로나",
    "favoritePlay": "원투 패스로 압박 풀어나오기",
    "hobby": "발로란트, 기타치기, 누워서 유튜브 보기",
    "favoritesong": "아이유 - 아이와 나의 바다",
    "drinkingCapacity": "반병",
    "drinkingHabit": "오바이트",
    "strength": "잘 웃음, 암기",
    "weakness": "낯가림, 소극적임",
    "favoriteFood": "치킨, 뿌셔뿌셔",
    "idealType": "귀엽고 밝고 말 많은 사람",
    "motto": "자신있게 살자",
    "tmi": "극I이지만 약간의 관종끼가 있음(?)",
    "image": "image2/logo.png",
    "group": "YB",
    "rolemodel": "손흥민"
  },
  {
    "name": "최지호",
    "generation": "47기",
    "position": "MF",
    "number": "#95",
    "age": "2005년생",
    "hometown": "충청남도 계룡시",
    "instagram": "ji.h.o.c",
    "department": "국제관계학과",
    "studentId": "25학번",
    "mbti": "ENFP",
    "favoriteTeam": "아마축구부",
    "favoritePlay": "패스 후 좋은 오프더볼",
    "hobby": "축구",
    "favoritesong": "BABYMONSTER- REALLY LIKE YOU",
    "drinkingCapacity": "없음",
    "drinkingHabit": "",
    "strength": "착하고 재미있다",
    "weakness": "미친 텐션",
    "favoriteFood": "치킨",
    "idealType": "하얗고 예쁜 사람",
    "motto": "인생은 자신감",
    "tmi": "생각보다 섬세함",
    "image": "image2/logo.png",
    "group": "YB",
    "rolemodel": "한지훈 선배님"
  },
  {
    "name": "양재원",
    "generation": "47기",
    "position": "LW",
    "number": "#44",
    "age": "2006년생",
    "hometown": "경기도 광명시",
    "instagram": "jaewon0617",
    "department": "신소재공학과",
    "studentId": "25학번",
    "mbti": "INTP",
    "favoriteTeam": "아스날",
    "favoritePlay": "사이드에서 1대1",
    "hobby": "축구하기, 축구보기",
    "favoritesong": "oasis - wonderwall",
    "drinkingCapacity": "1병",
    "drinkingHabit": "아무데서나 자기",
    "strength": "스피드",
    "weakness": "뛰다가 다리에 힘풀려서 넘어짐",
    "favoriteFood": "초밥",
    "idealType": "징징대지 않는 사람",
    "motto": "",
    "tmi": "올해 입대..",
    "image": "image2/logo.png",
    "group": "YB",
    "rolemodel": ""
  },
  {
    "name": "장재원",
    "generation": "47기",
    "position": "골잡이, 매니저 [Web발신]너는나를존중해야한다나는철원컵b팀의숭실대와의경기에서레전드발리슛을성공시켰으며여러경기에서꾸준히1인분이상의경기력을펼쳤고장산곶메기축구대회에서새내기로만구성된팀을죽음의조에서부터본선에진출시켰다동시에가을축제축구부부스에서테이블매니저총괄을도맡아하며성공적인부스운영에힘쓰었으며또한매주축구부회식때분위기메이커로서의자질을충분히증명하였다너는나를존중해야한다",
    "number": "#36",
    "age": "2004년생",
    "hometown": "서울특별시",
    "instagram": "jaeonii_official",
    "department": "인공지능학부",
    "studentId": "25학번",
    "mbti": "ESFJ",
    "favoriteTeam": "아마축구부",
    "favoritePlay": "숨막히는전방압박으로상대수비수의실수유도",
    "hobby": "롤하기",
    "favoritesong": "엠씨더맥스 - one love",
    "drinkingCapacity": "2병",
    "drinkingHabit": "시끄러워짐",
    "strength": "수준급 친화력",
    "weakness": "단점이 없다는 것",
    "favoriteFood": "회",
    "idealType": "귀여운 사람",
    "motto": "외유내강",
    "tmi": "나라를 수호하는 사회복무요원",
    "image": "image2/장재원.jpg",
    "group": "YB",
    "rolemodel": "장훈(부친)"
  },
  {
    "name": "천승원",
    "generation": "45기",
    "position": "MF",
    "number": "#97",
    "age": "2001년생",
    "hometown": "부산광역시",
    "instagram": "",
    "department": "전자전기컴퓨터공학부",
    "studentId": "",
    "mbti": "ENFJ",
    "favoriteTeam": "첼시",
    "favoritePlay": "티키타카",
    "hobby": "축구하기",
    "favoritesong": "임영웅 - 사랑은 늘 도망가",
    "drinkingCapacity": "한잔...",
    "drinkingHabit": "",
    "strength": "웃음이 많다",
    "weakness": "화가 없다",
    "favoriteFood": "아마축구부 운동끝나고 회식",
    "idealType": "성실하고 주변 사람 잘 챙기는 사람",
    "motto": "안되면 되게하라!!",
    "tmi": "아축 사랑합니당!!",
    "image": "image2/천승원.jpg",
    "group": "YB",
    "rolemodel": "부모님"
  },
  {
    "name": "신학철",
    "generation": "47기",
    "position": "MF, CB",
    "number": "#81",
    "age": "2005년생",
    "hometown": "인천광역시",
    "instagram": "tlsgkrcjf1212",
    "department": "물리학과",
    "studentId": "25학번",
    "mbti": "ENFP",
    "favoriteTeam": "아마축구부",
    "favoritePlay": "압박해서 볼 탈취, 뒷공간 커버",
    "hobby": "축구 시청 및 하기",
    "favoritesong": "SZA - Open Arms (Feat. Travis Scott)",
    "drinkingCapacity": "1병",
    "drinkingHabit": "같은 말 반복하기",
    "strength": "생각이 많다",
    "weakness": "생각이 많다",
    "favoriteFood": "페퍼로니 피자",
    "idealType": "사랑스러운 사람",
    "motto": "항상 최선을 다 하자",
    "tmi": "피자 한 판 다 먹는다",
    "image": "image2/logo.png",
    "group": "YB",
    "rolemodel": "페드리"
  },
  {
    "name": "도재민",
    "generation": "47기",
    "position": "MF",
    "number": "#64",
    "age": "2003년생",
    "hometown": "경상북도 경주",
    "instagram": "do._.jjaem",
    "department": "신소재공학과",
    "studentId": "22학번",
    "mbti": "ISFP",
    "favoriteTeam": "보루시아 도르트문트",
    "favoritePlay": "어려운 사이패스 난사하기",
    "hobby": "축구, 여행 유튜브 시청",
    "favoritesong": "유재하 - 내 마음에 비친 내 모습",
    "drinkingCapacity": "1병",
    "drinkingHabit": "눈감고 옆사람한테 기댐",
    "strength": "경청, 리액션, 양발패스",
    "weakness": "조용함, 몸싸움 들어오면 날라감",
    "favoriteFood": "치킨, 햄버거",
    "idealType": "잘 웃고 리액션 좋고 귀여우신 분",
    "motto": "평범하게 살자~",
    "tmi": "축구할 때마다 발가락 양말 신어요...ㅎ",
    "image": "image2/도재민.jpg",
    "group": "YB",
    "rolemodel": "최연우"
  },
  {
    "name": "박준영",
    "generation": "47기",
    "position": "FW",
    "number": "#80",
    "age": "2003년생",
    "hometown": "경기도 성남시",
    "instagram": "zun._0",
    "department": "전자전기컴퓨터공학부",
    "studentId": "22학번",
    "mbti": "자주 바뀜",
    "favoriteTeam": "토트넘 홋스퍼, FC서울",
    "favoritePlay": "간결하면서도 직진성 있는 플레이",
    "hobby": "축구, 인생고민",
    "favoritesong": "양홍원 - 실",
    "drinkingCapacity": "1병",
    "drinkingHabit": "귀가본능",
    "strength": "해야 할 일 다하기",
    "weakness": "해야 할 일 미루기",
    "favoriteFood": "부대찌개",
    "idealType": "느좋녀",
    "motto": "할 건 해야지",
    "tmi": "취준지옥 시작",
    "image": "image2/박준영.jpg",
    "group": "YB",
    "rolemodel": "세종대왕"
  },
  {
    "name": "정예준",
    "generation": "48기",
    "position": "MF, WB",
    "number": "#",
    "age": "2007년생",
    "hometown": "서울특별시",
    "instagram": "joon_0423",
    "department": "건축학과",
    "studentId": "26학번",
    "mbti": "INTP",
    "favoriteTeam": "바르셀로나",
    "favoritePlay": "",
    "hobby": "축구",
    "favoritesong": "Ondab - spin",
    "drinkingCapacity": "반병",
    "drinkingHabit": "부드러워지기",
    "strength": "열정적이다",
    "weakness": "잘 까먹는다",
    "favoriteFood": "양식 좋아합니다.",
    "idealType": "대화가 잘 되는 사람",
    "motto": "",
    "tmi": "활발하지만, 부끄럼이 많은 사람입니다.",
    "image": "image2/logo.png",
    "group": "YB",
    "rolemodel": "아빠"
  },
  {
    "name": "윤석현",
    "generation": "44기",
    "position": "LW, RW",
    "number": "#7(영구결번)",
    "age": "2003년생",
    "hometown": "전라남도 목포",
    "instagram": "seok.hyxxn",
    "department": "도시공학과",
    "studentId": "22학번",
    "mbti": "ISFJ",
    "favoriteTeam": "레스터시티",
    "favoritePlay": "드리블",
    "hobby": "운동",
    "favoritesong": "chilloop - someone just like u",
    "drinkingCapacity": "1병",
    "drinkingHabit": "조용히 잡니다",
    "strength": "리액션을 잘해준다?",
    "weakness": "리액션을 사람 가려서한다?",
    "favoriteFood": "스시",
    "idealType": "눈 예쁘고, 웃을때 예쁜 사람",
    "motto": "후회만 하지 말자",
    "tmi": "",
    "image": "image2/윤석현.jpg",
    "group": "YB",
    "rolemodel": "메시"
  },
  {
    "name": "김병철",
    "generation": "47기",
    "position": "RW",
    "number": "#97",
    "age": "2006년생",
    "hometown": "대구광역시",
    "instagram": "vchxle",
    "department": "자유전공-전자전기컴퓨터공학부",
    "studentId": "25학번",
    "mbti": "ENTP",
    "favoriteTeam": "아마축구부",
    "favoritePlay": "안쪽으로 파고들어 찬스만들기",
    "hobby": "유튜브 시청",
    "favoritesong": "SZA - Snooze",
    "drinkingCapacity": "반병",
    "drinkingHabit": "잠",
    "strength": "편안함",
    "weakness": "생각이 많음",
    "favoriteFood": "보쌈, 샤브샤브",
    "idealType": "티키타카 잘 되는 사람",
    "motto": "시작이 반이다",
    "tmi": "범이 맞후임 될 예정",
    "image": "image2/김병철.jpg",
    "group": "YB",
    "rolemodel": "라민 야말"
  },
  {
    "name": "고대영",
    "generation": "45기",
    "position": "CB",
    "number": "#25",
    "age": " ",
    "hometown": "서울특별시 동대문구",
    "department": "공간정보공학과",
    "studentId": "22학번",
    "graduationYear": "2026년",
    "favoriteTeam": "바이에른 뮌헨",
    "favoritePlay": "몸싸움",
    "hobby": "축구, 스노우보드, 헬스",
    "favoriteFood": "파스타, 엄청 단 도넛",
    "motto": "관계는 수단이 아닌 목적이다",
    "bestMoment": " ",
    "messageToJuniors": " ",
    "image": "image2/고대영.jpg",
    "group": "OB",
  },
  {
    "name": "정진우",
    "generation": "47기",
    "position": "LB",
    "number": "#56",
    "age": "2002년생",
    "hometown": "경기도 구리시",
    "instagram": "jungjinuuu",
    "department": "통계학과",
    "studentId": "23학번",
    "mbti": "ENTJ",
    "favoriteTeam": "맨체스터 시티",
    "favoritePlay": "중앙에서 빌드업하다가 상대 압박 세게 들어오면 사이드로의 빠른 전개와 오버래핑으로 사이드 찢는 플레이",
    "hobby": "헬스, 축구, 음주",
    "favoritesong": "창모 - 태지",
    "drinkingCapacity": "2~3병",
    "drinkingHabit": "인생에 대한 고찰",
    "strength": "생각이 많음, 열정 열정 열정",
    "weakness": "생각이 많음, 낯가림",
    "favoriteFood": "",
    "idealType": "예쁘고 자기 할 일 잘하고 잘 맞는 사람",
    "motto": "좋아하는 걸 하자, 좋아하는 것들에 미쳐서 살자",
    "tmi": "대학원 준비하면서 급속 노화 진행 중……",
    "image": "image2/logo.png",
    "group": "YB",
    "rolemodel": ""
  },
  {
    "name": "이성빈",
    "generation": "48기",
    "position": "FW",
    "number": "#89",
    "age": "2006년생",
    "hometown": "일산",
    "instagram": "real_binis",
    "department": "물리학과",
    "studentId": "26학번",
    "mbti": "ENFP",
    "favoriteTeam": "",
    "favoritePlay": "",
    "hobby": "",
    "favoritesong": "Hardlife(밴드)",
    "drinkingCapacity": "",
    "drinkingHabit": "",
    "strength": "",
    "weakness": "",
    "favoriteFood": "",
    "idealType": "",
    "motto": "",
    "tmi": "",
    "image": "image2/logo.png",
    "group": "YB",
    "rolemodel": "박지성"
  },
  {
    "name": "최명교",
    "generation": "43기",
    "position": "ST",
    "number": "#24",
    "age": "2002년생",
    "hometown": "서울 은평구",
    "instagram": "chlaudry",
    "department": "기계정보공학과",
    "studentId": "21학번",
    "mbti": "INFJ",
    "favoriteTeam": "아마축구부",
    "favoritePlay": "창의적으로 재치고 슈팅",
    "hobby": "mangoai.studio 개발하기",
    "favoritesong": "조용필 - 친구여",
    "drinkingCapacity": "3병",
    "drinkingHabit": "까불기",
    "strength": "기세, 스피드, 드리블, 슈팅",
    "weakness": "",
    "favoriteFood": "비지찌개",
    "idealType": "KYJ",
    "motto": "놀땐 놀고 일할땐 일하자",
    "tmi": "경험주의자. 머리 기르는중. 어울린다고 생각해서 기르는거 아님. 취직전 해보고 싶어서.",
    "image": "image2/최명교.jpg",
    "group": "YB",
    "rolemodel": "실패를 무서워하지 않고 도전하는 사람"
  },
  {
    "name": "오해찬",
    "generation": "48기",
    "position": "DF",
    "number": "#71",
    "age": "2000년생",
    "hometown": "광주광역시",
    "instagram": "55555._.haechan",
    "department": "건축학과",
    "studentId": "22학번",
    "mbti": "ENFP",
    "favoriteTeam": "PSG",
    "favoritePlay": "잘하는 플레이",
    "hobby": "축구, 게임",
    "favoritesong": "애국가",
    "drinkingCapacity": "1병",
    "drinkingHabit": "숙면",
    "strength": "말 잘들음",
    "weakness": "운동 할 땐 힘들어서 못 들음",
    "favoriteFood": "햄버거",
    "idealType": "ESTJ에 긴생머리",
    "motto": "긍정적으로 살기",
    "tmi": "24년도 편입학",
    "image": "image2/오해찬.jpg",
    "group": "YB",
    "rolemodel": "세종대왕"
  },
  {
    "name": "김승현",
    "generation": "48기",
    "position": "FW",
    "number": "#46",
    "age": "2003년생",
    "hometown": "광주광역시",
    "instagram": "sseung.g__k",
    "department": "국사학과",
    "studentId": "23학번",
    "mbti": "ESTJ",
    "favoriteTeam": "PSG",
    "favoritePlay": "침투 후 연계 or 마무리",
    "hobby": "음악 감상",
    "favoritesong": "유재하 - 지난 날",
    "drinkingCapacity": "소주 반병..?",
    "drinkingHabit": "많이 웃기😄",
    "strength": "친화력",
    "weakness": "감정 표현 부족",
    "favoriteFood": "나주곰탕",
    "idealType": "솔직한 사람",
    "motto": "항상 배울 마음을 갖자",
    "tmi": "",
    "image": "image2/logo.png",
    "group": "YB",
    "rolemodel": "다니 올모, 콜 파머"
  },
  {
    "name": "Matias",
    "generation": "48기",
    "position": "FW",
    "number": "#48",
    "age": "1999년생",
    "hometown": "Muraja",
    "instagram": "manestoo",
    "department": "",
    "studentId": "25학번",
    "mbti": "",
    "favoriteTeam": "Oulunsalon Pallo (OsPa)",
    "favoritePlay": "",
    "hobby": "Acoustic guitar",
    "favoritesong": "So Heavy I Fell Through the Earth",
    "drinkingCapacity": "",
    "drinkingHabit": "",
    "strength": "I sleep very well",
    "weakness": "I sleep too long",
    "favoriteFood": "꿀호떡",
    "idealType": "",
    "motto": "",
    "tmi": "",
    "image": "image2/logo.png",
    "group": "YB",
    "rolemodel": ""
  }
];